BYTES_PER_KIBIBYTE = 1024
BYTES_PER_MEBIBYTE = BYTES_PER_KIBIBYTE * BYTES_PER_KIBIBYTE
BYTES_PER_GIBIBYTE = BYTES_PER_MEBIBYTE * BYTES_PER_KIBIBYTE

SECONDS_PER_MINUTE = 60
SECONDS_PER_HOUR = SECONDS_PER_MINUTE * 60
SECONDS_PER_DAY = SECONDS_PER_HOUR * 24

DEFAULT_MAX_UPLOAD_BYTES = BYTES_PER_GIBIBYTE
DEFAULT_ADMIN_TOKEN_EXPIRES_SECONDS = SECONDS_PER_DAY
DEFAULT_DOWNLOAD_TOKEN_EXPIRES_SECONDS = SECONDS_PER_MINUTE * 5

FILE_IO_CHUNK_BYTES = BYTES_PER_MEBIBYTE

UUID_STR_LENGTH = 36
FILENAME_MAX_LENGTH = 255
FILE_PATH_MAX_LENGTH = 500
MIME_TYPE_MAX_LENGTH = 100
REMARK_MAX_LENGTH = 500
PASSWORD_HASH_MAX_LENGTH = 255

SHARE_CODE_LENGTH = 16
SHARE_CODE_MAX_RETRIES = 10
DOWNLOAD_TOKEN_TYPE = "download"
ADMIN_TOKEN_TYPE = "admin"
